### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by lkfranklin** [Nicola1971/OCx-Revo#1]
Hi Nicola,

Thank you for setting this up for me I really appreciate it. I've just installed and set everything up to give it a test but unfortunately when viewing the resource it just returns a blank page with an empty <head> and <body> tag, completely stripping off all other markup. I've checked the error log for any indication of what may have happened but nothing is reported.

Best,

**Comment by Nicola1971** [comment]
try to remove Evolution installer blocks from snippets
https://github.com/Nicola1971/OCx-Revo/blob/master/install/snippets/OCxProduct.tpl#L1-L10

tested now ocproducts (from this repository) on a local wamp Revo 2.5.1, works

![wgewqwoeucivaaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/17809343/3b3efebe-6616-11e6-9e17-87e5745dfbf4.png)

**Comment by lkfranklin** [comment]
Thank you that seems to have worked.
